### ISSUE TITLE
understand how site analytics have been set up,  validate that it is working.

### ISSUE THREAD

**Issue by klinehan1** [uva-bi-sdad/vdh_rural_health_site#3]
Google analytics currently being used

**Comment by thomasneil** [comment]
The typical code for Google Analytics is:

```
<!-- Global Site Tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXX-Y"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-XXXXXXX-Y');
</script>
```
and our page has the code in two parts:
The script here is in the head section of the page
```
<script type="application/javascript" src="https://www.googletagmanager.com/gtag/js?id=G-WSQPEF0573" async=""></script>
```
the rest of the code seems to kick in only after users explicitly opt-in (bottom left part of the page) seems to 
trigger a code in index.js
```
  function gtag() {
    if (site.settings.tracking) window.dataLayer.push(arguments)
  }
```

**Comment by thomasneil** [comment]
Easy Fix:
Modify index.html
Add the following content after line 12

```
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-WSQPEF0573');
</script>
```

But for a proper fix, will need to remove that opt-in section, will have to remove the javascript code that runs on trigger.

**Comment by thomasneil** [comment]
Also:
Github Button for analytics.
Does Google Analytics Count downloads of files on website, if not, how do we track.
Google Analytics Count hits on website
Are there Automated reports on Google Analytics? If yes, how do we auto-prepare and send it out

**Comment by thomasneil** [comment]
This is complete and now can be appended to new pages as part of the build process
